### ISSUE TITLE
[Request] possibility to overwrite arrays instead of merging

### ISSUE THREAD

**Issue by mesqueeb** [davidcalhoun/deep-object-assign-with-reduce#1]
I'd love the possibility to overwrite arrays instead of merging

**Comment by davidcalhoun** [comment]
Thanks for the suggestion!  I've kept things simple on purpose for now, so it doesn't support this.  This will probably be the first thing I implement in the case I expand it to support options.  Thanks!

**Comment by davidcalhoun** [comment]
Added support for this in `1.2.0`:

```js
import { deepAssignOptions } from 'deep-object-assign-with-reduce';
deepAssignOptions({overwriteArrays: true}, {}, { numbers: [1, 2] }, { numbers: [3, 4] });
// -> { numbers: [3, 4] }
```
