### ISSUE TITLE
Couldn't find a declaration file

### ISSUE THREAD

**Issue by Frimlik** [davidcalhoun/deep-object-assign-with-reduce#14]
In my constellation (Angular 13) after installing module
`npm install deep-object-assign-with-reduce`
and trying to import
`import { deepAssign } from 'deep-object-assign-with-reduce';`
an error shows up:
```
Could not find a declaration file for module 'deep-object-assign-with-reduce'. '<path>/node_modules/deep-object-assign-with-reduce/dist/deep-object-assign.umd.js' implicitly has an 'any' type.
```

**Comment by davidcalhoun** [comment]
Thanks for using this library - unfortunately I didn't write this in TypeScript, but in plain JavaScript.  You'll need to write the types on your side or configure TypeScript to ignore this library.
