### ISSUE TITLE
[Request] Keep first param reactive like Object.assign

### ISSUE THREAD

**Issue by mesqueeb** [davidcalhoun/deep-object-assign-with-reduce#2]
I'm looking for a "deep" Object.assign() that just like object assign will merge things onto the first Param. However, I need this first param (the target) to "be modified" (just like Object.assign) and not become a hard-clone.

Is this possible with your library?

**Comment by davidcalhoun** [comment]
Yep, this library mutates the first param just like `Object.assign`.  See this: https://github.com/davidcalhoun/deep-object-assign-with-reduce/blob/master/index.js#L26

Also see these tests: https://github.com/davidcalhoun/deep-object-assign-with-reduce/blob/master/test.js#L45
